GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/3

###

GET http://localhost:3001/api/persons/68785616e76351d2db101cfd

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/68a0f7b0046f93063bb803a8

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Grace Hopper",
  "number": "123-456-7890"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Mary Poppendieck",
  "number": "123-456-7890"
}