name: Deploy to Heroku (courseinfo)

on:
  push:
    branches: ["main"]
    paths:
      - 'part2/courseinfo/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set Heroku stack to container (only needed once)
        run: heroku stack:set container --app ${{ secrets.HEROKU_COURSEINFO_APP_NAME }}

      - name: Deploy with akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_COURSEINFO_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: part2/courseinfo
          docker_heroku_process_type: web

